
spring:
  datasource:
    url: jdbc:mariadb://26.108.69.145:3306/disciplinary_diary
    username: root
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
        format_sql: true

#    database-platform: org.mariadb.jdbc.Driver
server:
  port: 9750
